on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

permissions: read-all

env:
  GH_TOKEN: ${{ secrets.E2E_GO_TOKEN }}
  ISSUE_REPOSITORY: slsa-framework/slsa-github-generator
  # ISSUE_REPOSITORY: laurentsimon/slsa-on-github-test
  # WARNING: update build job if CONFIG_FILE changes.
  CONFIG_FILE: .github/configs-go/config-noldflags.yml

jobs:
  build-builder:
    runs-on: ubuntu-latest
    env:
      ARTIFACT: builder
      AFTER: 135
      FOR: 45
      EVERY: 5
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0
      # Note: build-dry and build should fail. It's hard to tell which failed,
      # but they both should. It's good enough to verify that the re-usable workflow always fails.
      - uses: ./.github/actions/tamper-artifact

  build:
    permissions:
      id-token: write # For signing.
      contents: write # For asset uploads.
      actions: read # For the entrypoint.
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@main
    with:
      go-version: 1.18
      # We cannot use ${{ env.CONFIG_FILE }} because env variables are not available.
      config-file: .github/configs-go/config-noldflags.yml
      compile-builder: true

  #   build:
  #     runs-on: ubuntu-latest
  #     steps:
  #       - run: |
  #           exit 1

  if-succeeded:
    runs-on: ubuntu-latest
    needs: [build]
    if: needs.build.result == 'success'
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0
      - run: |
          set -euo pipefail

          # The builder should fail if the builder is tampered with.
          ./.github/workflows/scripts/e2e-report-failure.sh

  if-failed:
    runs-on: ubuntu-latest
    needs: [build]
    if: always() && needs.build.result == 'failure'
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0
      - run: |
          set -euo pipefail

          # The builder should fail if the builder is tampered with.
          ./.github/workflows/scripts/e2e-report-success.sh
