on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions: read-all

concurrency: "e2e.delegator-lowperms.workflow_dispatch.main.default.slsa3"

env:
  GH_TOKEN: ${{ secrets.E2E_GENERIC_TOKEN }}
  ISSUE_REPOSITORY: slsa-framework/slsa-github-generator

jobs:

  # Dispatch
  ################################################################################
  dispatch:
    runs-on: ubuntu-latest
    # NOTE: workflows are only scheduled on the main branch.
    if: github.event_name == 'schedule'
    permissions:
      actions: write
      contents: write
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - run: ./.github/workflows/scripts/e2e-dispatch.sh

  if-dispatch-failed:
    runs-on: ubuntu-latest
    needs: [dispatch]
    if: always() && github.event_name == 'schedule' && needs.dispatch.result != 'success'
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - run: ./.github/workflows/scripts/e2e-report-failure.sh

  # Main workflow
  ################################################################################
  build:
    if: github.event_name == 'workflow_dispatch'
    permissions:
      id-token: write # For signing
      contents: write # For asset uploads
      packages: write # To write to github packages
      actions: read
    # v2.0.0 uses the delegator_lowperms-generic_slsa3.yml
    # See https://github.com/slsa-framework/example-trw/blob/v2.0.0/.github/workflows/builder_example_slsa3.yml
    uses: slsa-framework/example-trw/.github/workflows/builder_example_slsa3.yml@v2.0.0
    with:
      artifact: my-artifact
      content: "hello world delegator_lowperms_slsa3"
    secrets:
      # NOTE: this password is set to 'delegator-password'.
      password: ${{ secrets.DELEGATOR_PASSWORD }}

  verify:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: slsa-framework/slsa-github-generator/actions/delegator/secure-download-folder@main
        with:
          name: "${{ needs.build.outputs.artifact-download-name }}" # NOTE: This is randomized 'my-artifact'.
          sha256: "${{ needs.build.outputs.artifact-download-sha256 }}"
          path: "."
      - uses: slsa-framework/example-trw/download/attestation@v2.0.0 # Use same version as the builder.
        with:
          name: "${{ needs.build.outputs.provenance-download-name }}"
          sha256: "${{ needs.build.outputs.provenance-download-sha256 }}"
      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version: "1.18"
      - env:
          # NOTE: We move the artifact because the verification script
          # check that the subject name matches the filename.
          ARTIFACT: "${{ needs.build.outputs.artifact }}"
        run: |
          mv "artifacts/${ARTIFACT}" .
      - env:
          BINARY: "${{ needs.build.outputs.artifact }}"
          PROVENANCE: "${{ needs.build.outputs.provenance-download-name }}/${{ needs.build.outputs.artifact }}.build.slsa" # This is defined by the builder.
          BUILDER_ID: "https://github.com/slsa-framework/example-trw/.github/workflows/builder_example_slsa3.yml"
          BUILDER_TAG: "v2.0.0"
        run: ./.github/workflows/scripts/e2e.delegator.default.verify.sh

  if-succeeded:
    runs-on: ubuntu-latest
    needs: [build, verify]
    if: github.event_name == 'workflow_dispatch' && needs.build.result == 'success' && needs.verify.result == 'success'
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - run: ./.github/workflows/scripts/e2e-report-success.sh

  if-failed:
    runs-on: ubuntu-latest
    needs: [build, verify]
    if: always() && github.event_name == 'workflow_dispatch' && (needs.build.result == 'failure' || needs.verify.result == 'failure')
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - run: ./.github/workflows/scripts/e2e-report-failure.sh
