on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions: read-all

concurrency: "e2e.generic.workflow_dispatch.main.large-subjects.slsa3"

env:
  GH_TOKEN: ${{ secrets.E2E_GENERIC_TOKEN }}
  ISSUE_REPOSITORY: slsa-framework/slsa-github-generator

jobs:
  dispatch:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    permissions:
      actions: write
      contents: write
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - run: ./.github/workflows/scripts/e2e-dispatch.sh

  build:
    if: github.event_name == 'workflow_dispatch'
    outputs:
      binary-name: ${{ steps.build.outputs.binary-name }}
      handle: ${{ steps.sharedfile.outputs.handle }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build artifact
        id: build
        run: |
          echo "hello world" > hello
          echo "binary-name=hello" >> "${GITHUB_OUTPUT}"
      - name: Upload binary
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: ${{ steps.build.outputs.binary-name }}
          path: ${{ steps.build.outputs.binary-name }}
          if-no-files-found: error
          retention-days: 5
      - name: Generate hash
        shell: bash
        id: hash
        env:
          BINARY_NAME: ${{ steps.build.outputs.binary-name }}
        run: |
          set -euo pipefail

          outfile="tmp_file"
          sha256sum "$BINARY_NAME" > "$outfile"

          # Create one subject for the BINARY_NAME, and add 4096 random subjects.
          counter=0
          while [ $counter -le 4096 ]; do
            subject="subject-$counter"
            echo "ee819cb7811108e781333b6414c683950239dc546f126b4a058a7af5c61edd02  $subject" >> "$outfile"
            counter=$((counter + 1))
            echo -n .
          done

          base64 -w0 "${outfile}" > digests.txt

      - name: Share the file
        id: sharedfile
        uses: slsa-framework/slsa-github-generator/actions/generator/generic/create-base64-subjects-from-file@main
        with:
          path: digests.txt

  provenance:
    if: github.event_name == 'workflow_dispatch'
    needs: [build]
    permissions:
      id-token: write # For signing.
      contents: write # For asset uploads.
      actions: read # For the entrypoint.
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@main
    with:
      base64-subjects-as-file: "${{ needs.build.outputs.handle }}"
      compile-generator: true

  verify:
    runs-on: ubuntu-latest
    needs: [build, provenance]
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/download-artifact@e9ef242655d12993efdcda9058dee2db83a2cb9b
        with:
          name: ${{ needs.build.outputs.binary-name }}
      - uses: actions/download-artifact@e9ef242655d12993efdcda9058dee2db83a2cb9b
        with:
          name: ${{ needs.provenance.outputs.attestation-name }}
      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version: "1.18"
      - env:
          BINARY: ${{ needs.build.outputs.binary-name }}
          PROVENANCE: ${{ needs.provenance.outputs.attestation-name }}
        run: ./.github/workflows/scripts/e2e.generic.default.verify.sh

  if-succeeded:
    runs-on: ubuntu-latest
    needs: [build, provenance, verify]
    if: github.event_name == 'workflow_dispatch' && needs.build.result == 'success' && needs.provenance.result == 'success' && needs.verify.result == 'success'
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - run: ./.github/workflows/scripts/e2e-report-success.sh

  if-failed:
    runs-on: ubuntu-latest
    needs: [build, provenance, verify]
    if: always() && github.event_name == 'workflow_dispatch' && (needs.build.result == 'failure' || needs.provenance.result == 'failure' || needs.verify.result == 'failure')
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - run: ./.github/workflows/scripts/e2e-report-failure.sh
