# This workflow deletes old releases created by e2e tests to keep the number
# managable.

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions: read-all

env:
  GH_TOKEN: ${{ secrets.E2E_GENERIC_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to delete tags
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Delete old releases
        id: build
        run: ./.github/workflows/scripts/e2e-delete-old-releases.sh
